### ISSUE TITLE
Error: error:0308010C:digital envelope routines::unsupported

### ISSUE THREAD

**Issue by marek22k** [tobspr-games/shapez.io#1575] opened 2023-11-04 21:03 UTC
Hello,

after I applied a [workaround](https://github.com/tobspr-games/shapez.io/issues/1574#issuecomment-1793553084), the game starts but does not load in the browser. There it gets stuck at "Downloading Game Files" and the following output appears in the console:
```
$ yarn gulp
yarn run v1.22.19
$ gulp
Please set SHAPEZ_CLI_SERVER_HOST
Please set SHAPEZ_CLI_ALPHA_FTP_USER
Please set SHAPEZ_CLI_ALPHA_FTP_PW
Please set SHAPEZ_CLI_STAGING_FTP_USER
Please set SHAPEZ_CLI_STAGING_FTP_PW
Please set SHAPEZ_CLI_LIVE_FTP_USER
Please set SHAPEZ_CLI_LIVE_FTP_PW
Please set SHAPEZ_CLI_APPLE_ID
Please set SHAPEZ_CLI_APPLE_CERT_NAME
Please set SHAPEZ_CLI_GITHUB_USER
Please set SHAPEZ_CLI_GITHUB_TOKEN
[22:00:22] Using gulpfile ~/shapez.io/gulp/gulpfile.js
[22:00:22] Starting 'default'...
[22:00:22] Starting 'main.serveDev'...
[22:00:22] Starting 'build.dev'...
[22:00:22] Starting 'utils.cleanup'...
[22:00:22] Starting 'utils.cleanBuildFolder'...
[22:00:22] Finished 'utils.cleanBuildFolder' after 28 ms
[22:00:22] Starting 'utils.cleanImageBuildFolder'...
[22:00:22] Finished 'utils.cleanImageBuildFolder' after 2.23 ms
[22:00:22] Starting 'utils.cleanBuildTempFolder'...
[22:00:22] Finished 'utils.cleanBuildTempFolder' after 5.51 ms
[22:00:22] Finished 'utils.cleanup' after 37 ms
[22:00:22] Starting 'utils.copyAdditionalBuildFiles'...
[22:00:22] Finished 'utils.copyAdditionalBuildFiles' after 2.89 ms
[22:00:22] Starting 'localConfig.findOrCreate'...
[22:00:22] Finished 'localConfig.findOrCreate' after 226 μs
[22:00:22] Starting 'imgres.buildAtlas'...
openjdk version "17.0.7" 2023-04-18
OpenJDK Runtime Environment (build 17.0.7+7-Debian-1deb11u1)
OpenJDK 64-Bit Server VM (build 17.0.7+7-Debian-1deb11u1, mixed mode, sharing)
[22:00:26] Finished 'imgres.buildAtlas' after 3.69 s
[22:00:26] Starting 'imgres.atlasToJson'...
Processing: /home/marek/shapez.io/res_built/atlas/atlas0_hq.atlas
Processing: /home/marek/shapez.io/res_built/atlas/atlas0_lq.atlas
Processing: /home/marek/shapez.io/res_built/atlas/atlas0_mq.atlas
[22:00:26] Finished 'imgres.atlasToJson' after 8.56 ms
[22:00:26] Starting 'imgres.atlas'...
[22:00:26] Finished 'imgres.atlas' after 16 ms
[22:00:26] Starting 'sounds.dev'...
[22:00:26] Starting 'sounds.buildall'...
[22:00:26] Starting 'sounds.music'...
[22:00:26] Starting 'sounds.sfx'...
[22:00:26] Starting 'sounds.sfxGenerateSprites'...
[
  '/home/marek/shapez.io/res_raw/sounds/sfx/badge_notification.wav',
  '/home/marek/shapez.io/res_raw/sounds/sfx/copy.wav',
  '/home/marek/shapez.io/res_raw/sounds/sfx/destroy_building.wav',
  '/home/marek/shapez.io/res_raw/sounds/sfx/dialog_error.wav',
  '/home/marek/shapez.io/res_raw/sounds/sfx/dialog_ok.wav',
  '/home/marek/shapez.io/res_raw/sounds/sfx/level_complete.wav',
  '/home/marek/shapez.io/res_raw/sounds/sfx/place_belt.wav',
  '/home/marek/shapez.io/res_raw/sounds/sfx/place_building.wav',
  '/home/marek/shapez.io/res_raw/sounds/sfx/ui_click.wav',
  '/home/marek/shapez.io/res_raw/sounds/sfx/ui_error.wav',
  '/home/marek/shapez.io/res_raw/sounds/sfx/ui_swish_hide.wav',
  '/home/marek/shapez.io/res_raw/sounds/sfx/ui_swish_show.wav'
] undefined
File added OK {
  file: '/tmp/user/1000/audiosprite.8430233410344852',
  duration: 0.9675283446712019
}
Silence gap added { duration: 0.13247165532879815 }
File added OK {
  file: '/tmp/user/1000/audiosprite.7899340125177841',
  duration: 0.18081632653061225
}
Silence gap added { duration: 0.9191836734693878 }
File added OK {
  file: '/tmp/user/1000/audiosprite.4026079750476801',
  duration: 0.4672108843537415
}
Silence gap added { duration: 0.6327891156462585 }
File added OK {
  file: '/tmp/user/1000/audiosprite.9808907910259232',
  duration: 0.19507936507936507
}
Silence gap added { duration: 0.9049206349206349 }
[22:00:27] Finished 'sounds.music' after 1.18 s
File added OK {
  file: '/tmp/user/1000/audiosprite.2601706825957837',
  duration: 0.8804535147392291
}
Silence gap added { duration: 0.21954648526077095 }
File added OK {
  file: '/tmp/user/1000/audiosprite.5407114270736857',
  duration: 2.119387755102041
}
Silence gap added { duration: 0.980612244897959 }
File added OK {
  file: '/tmp/user/1000/audiosprite.3129777428288256',
  duration: 0.06380952380952382
}
Silence gap added { duration: 1.0361904761904763 }
File added OK {
  file: '/tmp/user/1000/audiosprite.923513080037822',
  duration: 0.30984126984126986
}
Silence gap added { duration: 0.7901587301587302 }
File added OK {
  file: '/tmp/user/1000/audiosprite.49202629993877767',
  duration: 0.11297052154195011
}
Silence gap added { duration: 0.9870294784580499 }
File added OK {
  file: '/tmp/user/1000/audiosprite.4844028864166523',
  duration: 0.3057369614512472
}
Silence gap added { duration: 0.7942630385487528 }
File added OK {
  file: '/tmp/user/1000/audiosprite.8255827215868912',
  duration: 0.08541950113378685
}
Silence gap added { duration: 1.0145804988662133 }
File added OK {
  file: '/tmp/user/1000/audiosprite.25194572617945865',
  duration: 0.1127891156462585
}
Silence gap added { duration: 0.9872108843537415 }
Exported mp3 OK { file: '/tmp/user/1000/sfx.mp3' }
[22:00:28] Finished 'sounds.sfxGenerateSprites' after 1.8 s
[22:00:28] Starting 'sounds.sfxOptimize'...
[22:00:28] Finished 'sounds.sfxOptimize' after 230 ms
[22:00:28] Starting 'sounds.sfxCopyAtlas'...
[22:00:28] Finished 'sounds.sfxCopyAtlas' after 2.2 ms
[22:00:28] Finished 'sounds.sfx' after 2.05 s
[22:00:28] Finished 'sounds.buildall' after 2.05 s
[22:00:28] Starting 'sounds.copy'...
[22:00:28] Finished 'sounds.copy' after 22 ms
[22:00:28] Finished 'sounds.dev' after 2.07 s
[22:00:28] Starting 'imgres.copyImageResources'...
[22:00:28] Finished 'imgres.copyImageResources' after 443 ms
[22:00:28] Starting 'imgres.copyNonImageResources'...
[22:00:28] Finished 'imgres.copyNonImageResources' after 11 ms
[22:00:28] Starting 'translations.fullBuild'...
[22:00:28] Starting 'translations.convertToJson'...
[22:00:28] Finished 'translations.convertToJson' after 124 ms
[22:00:28] Finished 'translations.fullBuild' after 124 ms
[22:00:28] Starting 'css.dev'...
[22:00:28] Starting 'css.main.dev'...
[22:00:28] Starting 'css.resources.dev'...
[22:00:29] Finished 'css.main.dev' after 1.08 s
[22:00:29] Finished 'css.resources.dev' after 1.08 s
[22:00:29] Finished 'css.dev' after 1.08 s
[22:00:29] Starting 'html.dev'...
[22:00:30] Finished 'html.dev' after 300 ms
[22:00:30] Finished 'build.dev' after 7.78 s
[22:00:30] Starting '<anonymous>'...
[22:00:30] Starting 'js.dev.watch'...
[BS] Access URLs:
 ----------------------------
 Local: http://localhost:3005
 ----------------------------
    UI: http://localhost:3001
 ----------------------------
[BS] Serving files from: /home/marek/shapez.io/build
[BS] Serving files from: /home/marek/shapez.io/mod_examples
Error: error:0308010C:digital envelope routines::unsupported
    at new Hash (node:internal/crypto/hash:71:19)
    at Object.createHash (node:crypto:140:10)
    at module.exports (/home/marek/shapez.io/gulp/node_modules/webpack/lib/util/createHash.js:135:53)
    at NormalModule._initBuildHash (/home/marek/shapez.io/gulp/node_modules/webpack/lib/NormalModule.js:417:16)
    at handleParseError (/home/marek/shapez.io/gulp/node_modules/webpack/lib/NormalModule.js:471:10)
    at /home/marek/shapez.io/gulp/node_modules/webpack/lib/NormalModule.js:503:5
    at /home/marek/shapez.io/gulp/node_modules/webpack/lib/NormalModule.js:358:12
    at /home/marek/shapez.io/gulp/node_modules/loader-runner/lib/LoaderRunner.js:373:3
    at iterateNormalLoaders (/home/marek/shapez.io/gulp/node_modules/loader-runner/lib/LoaderRunner.js:214:10)
    at iterateNormalLoaders (/home/marek/shapez.io/gulp/node_modules/loader-runner/lib/LoaderRunner.js:221:10)
    at /home/marek/shapez.io/gulp/node_modules/loader-runner/lib/LoaderRunner.js:236:3
    at runSyncOrAsync (/home/marek/shapez.io/gulp/node_modules/loader-runner/lib/LoaderRunner.js:130:11)
    at iterateNormalLoaders (/home/marek/shapez.io/gulp/node_modules/loader-runner/lib/LoaderRunner.js:232:2)
    at iterateNormalLoaders (/home/marek/shapez.io/gulp/node_modules/loader-runner/lib/LoaderRunner.js:221:10)
    at /home/marek/shapez.io/gulp/node_modules/loader-runner/lib/LoaderRunner.js:236:3
    at runSyncOrAsync (/home/marek/shapez.io/gulp/node_modules/loader-runner/lib/LoaderRunner.js:130:11)
```

**Comment by marek22k** [comment] 2023-11-04 21:06
Workaround:
Source: https://stackoverflow.com/questions/69692842/error-message-error0308010cdigital-envelope-routinesunsupported
Downgrade to v16:
```
nvm install v16
npm -g install yarn
```

**Comment by EmeraldBlock** [comment] 2023-11-04 23:24
possible duplicate of #1473 (thanks for logs!)

**Closed by EmeraldBlock** 2023-11-04 23:24 UTC

**Comment by josch** [comment] 2024-12-21 00:24
> possible duplicate of #1473 (thanks for logs!)

Thank you, following the advice in that issue and starting the game like this:

    NODE_OPTIONS=--openssl-legacy-provider yarnpkg gulp

Indeed made the game start and playable with nodejs 18.19.0+dfsg-6~deb12u2 on Debian Bookworm. Thank you!
