### ISSUE TITLE
[Feature Request] - Better Markers

### ISSUE THREAD

**Issue by AEAEAEAE4343** [tobspr-games/shapez.io#596] opened 2020-08-26 21:30 UTC
Markers currently support a shape icon or a text label. I think there should be an option to have both. e.g:
![shapez marker icon](https://user-images.githubusercontent.com/34800109/91359025-18109d80-e7f4-11ea-811f-4a44e6d4b828.png)

**Comment by PyMaster22** [comment] 2020-08-27 23:25
Good idea.

**Comment by EmeraldBlock** [comment] 2022-11-13 05:28
Duplicate of #559

**Closed** 2022-11-13 17:24 UTC
Labels: duplicate
