### ISSUE TITLE
[Feature Request] Combine Normal and sandbox mode

### ISSUE THREAD

**Issue by theMasterMindsupersmart** [tobspr-games/shapez.io#1311] opened 2021-11-04 20:51 UTC
Can you make it so when you start a save file, it just gives the option to start in sandbox or normal mode?

**Comment by EmeraldBlock** [comment] 2021-11-04 21:28
duplicate of #646

**Comment by dengr1065** [comment] 2022-11-10 08:55
Closing as described in https://github.com/tobspr-games/shapez.io/issues/1311#issuecomment-961441536

**Closed by dengr1065** 2022-11-10 08:55 UTC
