### ISSUE TITLE
Windows: Alt+F4 should quit the game

### ISSUE THREAD

**Issue by ekevoo** [tobspr-games/shapez.io#577] opened 2020-08-19 05:34 UTC
The vast majority of Windows games go poof within one second when I type Alt+F4. I really like this. The exceptions like to ask for a silly "are you sure" as if it was a key combination that could ever be pressed accidentally.

In Shapez.io, at least the Steam version, nothing happens when I press Alt+F4. The game doesn't react at all. Why?

**Comment by dengr1065** [comment] 2020-08-19 12:01
Duplicate of #528

**Closed** 2022-11-13 04:57 UTC
Labels: duplicate
