### ISSUE TITLE
Feature Request: Allow copy and paste of standard and wires layer simultaneously 

### ISSUE THREAD

**Issue by UnicycleUnicorn** [tobspr-games/shapez.io#1070] opened 2021-02-22 19:40 UTC
This would be very beneficial for lining up larger blueprints with their wire counterparts.

**Comment by EmeraldBlock** [comment] 2021-02-22 20:37
Duplicate of #881

**Comment by dengr1065** [comment] 2022-11-11 15:58
Closing as described above.

**Closed by dengr1065** 2022-11-11 15:58 UTC
Labels: feature-request, duplicate
