### ISSUE TITLE
Level complete clears placing tool

### ISSUE THREAD

**Issue by nevjmac** [tobspr-games/shapez.io#1151] opened 2021-04-23 20:30 UTC
Once you've got a MAM running and clearing levels relatively quickly. Everytime the pop up comes up saying level complete it clears whatever you were in the process of building if holding shift, or whatever you have in selected to build

**Comment by EmeraldBlock** [comment] 2021-04-23 20:33
Duplicate of #998

**Closed** 2022-11-10 15:03 UTC
Labels: duplicate
