### ISSUE TITLE
Belts placed wrong when using blueprints

### ISSUE THREAD

**Issue by Tylorean** [tobspr-games/shapez.io#1150] opened 2021-04-23 08:39 UTC
when i place a bleuprint, it often places the belt wrong. Dev, pls add setting to toggle the automatic belt orientation.
thx
![Screenshot 2021-04-23 101610](https://user-images.githubusercontent.com/83063627/115844514-32048d80-a420-11eb-9d65-2c61f82e36c9.png)

**Comment by EmeraldBlock** [comment] 2021-04-23 14:09
Duplicate of #214

**Closed** 2022-11-10 08:57 UTC
