### ISSUE TITLE
error code because it can't find any github revisions

### ISSUE THREAD

**Issue by Goldie323** [tobspr-games/shapez.io#1587] opened 2024-01-06 09:53 UTC
I'm on ubuntu and tried to build from source and got to the part where you run "yarn gulp" and it got an error code when it tried to run "git rev-parse --short HEAD" it said "fatal: Needed a single revision" and I even tried to run "git fetch origin" to maybe fix it but no luck and I want to know how to fix it.

**Comment by Goldie323** [comment] 2024-01-06 11:29
I fixed the issue by using git clone to get the repo instead of download as zip from the website and that fixed it

**Comment by EmeraldBlock** [comment] 2024-01-06 19:02
duplicate of #1284 

please close the issue yourself if you've fixed it! glad you did figure it out though :)

**Closed by EmeraldBlock** 2024-01-06 19:02 UTC

**Comment by EmeraldBlock** [comment] 2024-01-06 19:04
duplicate of #1284
